### ISSUE TITLE
ค้างบ่อยมากครับ

### ISSUE THREAD

**Issue by otaroo** [goragod/edocument#1]
เข้าหน้าบางหน้าแล้วขึ้น
Sorry, cannot find a page called Please check the URL or try the call again.

จากนั้นก็คลิกไปหน้าไหนอีกไม่ได้เรยครับ

**Comment by goragodwiriya** [comment]
คำถามกว้างมากครับ 
ถ้าอยู่บน Server จริงๆ สามารถส่งข้อมูล Host ให้ผมเข้าไปดูให้ได้ครับ ทางอีเมล์
หรือลองอัปเกรดตอนนี้เผื่อปัญหาจะได้รับการแก้ไขแล้วในเวอร์ชั่นปัจจุบัน

**Comment by goragodwiriya** [comment]
ลองอัปเดทดูนะครับ ไม่แน่ใจว่าเป็นปัญหาเดียวกันกับที่เพิ่งแก้ไขไปหรือเปล่า
